name: Lint YAML

on: [push]

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: lint-yaml
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_data: |
            yaml-files:
              - '*.yaml'
              - '*.yml'
              - '*.yml.j2'
            rules:
              indentation:
                spaces: consistent
                indent-sequences: consistent
                level: warning
              hyphens:
                max-spaces-after: 1
              trailing-spaces: {}
